apiVersion: apps/v1
kind: Deployment
metadata:
  name: rh-management
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app-rh
          ports:
            - containerPort: 8081
#          container-name :
#            app: web
#
